export {default as About} from "./About"
export {default as Compétences} from "./Compétences"
export {default as Contact} from "./Contact"
export {default as Projets} from "./Projets"
export {default as Services} from "./Services"
export {default as Footer} from "./Footer"